### ISSUE TITLE
rename surrealdb.world to surrealdb.com

### ISSUE THREAD

**Issue by szabgab** [surrealdb/www.surrealdb.world#2]
While this repo has references to surrealdb.world it seem that the site is now hosted on https://surrealdb.com/ It might be a good idea to rename thing here to avoid confusion.

**Comment by tobiemh** [comment]
Hi @szabgab the https://surrealdb.world website is actually no longer live. The old pages will eventually be made live again on the main https://surrealdb.com site (which is housed in a private repository). In the meantime I'm going to delete this repository while these pages get added to the main website.
